version: "3.9"
services:
  fastapi:
    build: .
    container_name: job-search-fastapi
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: job-search-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobsearch
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d jobsearch"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
