"""add company size

Revision ID: de4ffd17216b
Revises: 67e9a86035a0
Create Date: 2025-06-09 22:19:02.840036

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de4ffd17216b"
down_revision: Union[str, None] = "67e9a86035a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_sizes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("size", sa.String(), nullable=False),
        sa.Column("min_employees", sa.Integer(), nullable=True),
        sa.Column("max_employees", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_company_sizes_id"), "company_sizes", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_company_sizes_id"), table_name="company_sizes")
    op.drop_table("company_sizes")
    # ### end Alembic commands ###
